name: Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install apt dependencies
      run: sudo apt-get install python3-pip clang clang-format clang-tidy

    - name: Install pip dependencies
      run: pip install cmake-format --user

    - name: Build Debug
      # Build your program with the given configuration
      run: make dev

    - name: Test
      run: make test
      
    - name: Analyzer
      run: make tidy
